# Site settings
title: pyrapple.gitHub.io
email: davipoir@gmail.com
description: personal website, gathered research and development projects

# baseurl is defined to match GitHub's path while handling relative links
# during local tests with Jekyll server with the --baseurl '' option.
# (see https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908)
baseurl: ""
url: "https://pyrapple.github.io"

github_username: pyrapple

# Build settings
markdown: kramdown

# Define code highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge
