# Site settings
title: EVERTims Website
email: evertims@gmail.com
description: > # this means to ignore newlines until "baseurl:"
 EVERTims is a framework for real-time auralization in Virtual Reality

# baseurl is defined to match GitHub's path while handling relative links
# during local tests with Jekyll server with the --baseurl '' option.
# (see https://github.com/jekyll/jekyll/issues/332#issuecomment-18952908)
baseurl: ""
url: "" # the base hostname & protocol for your site

# twitter_username: volnyio
github_username:  EVERTims

# Build settings
markdown: kramdown

# Define code highlighter
kramdown:
  input: GFM
  syntax_highlighter: rouge
